### ISSUE TITLE
Spurious "Failed Render" error message

### ISSUE THREAD

**Issue by msandy** [LogicReinc/LogicReinc.BlendFarm#32]
I am running the server on Windows and the client on Mac (latest versions as of one hour ago). Upon completion of a render, a message pops up on the client indicating a *Failed render due to: A generic error occurred in GDI+.*:
<img width="529" alt="Failed Render error message screenshot" src="https://user-images.githubusercontent.com/12552462/162555820-818fde8a-d777-4380-874e-2f69f4414fd4.png">

Despite this message, the render appears to have completed successfully and is visible in the client. Likewise, the console on the server shows:

```
SUCCESS: <guid>
BATCH_COMPLETE
Blender quit
```

Obviously GDI indicates this is a message from the server side, but there is no evidence of an actual error. It also happens regardless of whether I choose CUDA or CPU rendering. One possible quirk about my host is that my last connection to the Windows machine was via RDP, so the "display" will show as a virtual display of sorts.

**Comment by LogicReinc** [comment]
GDI+ is actually a client side issue for MacOS specifically, it has to do with the previewing or merging code I believe. It should not affect renders, and can be ignored.
I thought I fixed it but apparently not.
Either way, you should be able to ignore that error, I will look into it again and see if I can filter it out.

**Comment by szabeszg** [comment]
Still an issue with Blender 4.0.2 and macOS 12

**Comment by JakeGilesPhillips** [comment]
Still an issue for me, servers on windows, client on macos - happens right as the final composite occurs, because I have multiple servers, the image fails to composite too, only shows the section the last completing server handled.
